export const categories = [
  { name: 'AC Repair', icon: '🛠️' },
  { name: 'Salon', icon: '💇‍♀️' },
  { name: 'Plumbing', icon: '🚰' },
  { name: 'Cleaning', icon: '🧼' },
  { name: 'Electrician', icon: '💡' },
  { name: 'Pest Control', icon: '🐜' },
  { name: 'Carpentry', icon: '🪚' },
  { name: 'Appliance Repair', icon: '🔧' },
  { name: 'Painting', icon: '🎨' },
  { name: 'Laundry', icon: '🧺' },
  { name: 'Car Wash', icon: '🚗' },
  { name: 'Home Deep Cleaning', icon: '🧹' },
];

export const topProviders = [
  {
    name: 'Rajesh Kumar',
    experience: '5 yrs',
    rating: 4.9,
    service: 'AC Repair',
    price: 399,
    image: '/assets/users/rajesh.jpg',
  },
  {
    name: 'Sneha Sharma',
    experience: '3 yrs',
    rating: 4.8,
    service: 'Salon Services',
    price: 299,
    image: '/assets/users/sneha.jpg',
  },
  {
    name: 'Aman Verma',
    experience: '4 yrs',
    rating: 4.7,
    service: 'Plumbing',
    price: 349,
    image: '/assets/users/aman.jpg',
  },
  {
    name: 'Neha Joshi',
    experience: '2 yrs',
    rating: 4.6,
    service: 'Cleaning',
    price: 299,
    image: '/assets/users/neha.jpg',
  },
  {
    name: 'Deepak Mehta',
    experience: '6 yrs',
    rating: 4.9,
    service: 'Electrician',
    price: 399,
    image: '/assets/users/deepak.jpg',
  },
  {
    name: 'Komal Yadav',
    experience: '3 yrs',
    rating: 4.8,
    service: 'Pest Control',
    price: 459,
    image: '/assets/users/komal.jpg',
  },
  {
    name: 'Vikram Singh',
    experience: '7 yrs',
    rating: 4.7,
    service: 'Carpentry',
    price: 499,
    image: '/assets/users/vikram.jpg',
  },
  {
    name: 'Ritu Arora',
    experience: '2 yrs',
    rating: 4.6,
    service: 'Appliance Repair',
    price: 399,
    image: '/assets/users/ritu.jpg',
  },
  {
    name: 'Farhan Ali',
    experience: '5 yrs',
    rating: 4.9,
    service: 'Painting',
    price: 599,
    image: '/assets/users/farhan.jpg',
  },
  {
    name: 'Anjali Kapoor',
    experience: '3 yrs',
    rating: 4.7,
    service: 'Laundry',
    price: 259,
    image: '/assets/users/anjali.jpg',
  },
  {
    name: 'Ramesh Pawar',
    experience: '4 yrs',
    rating: 4.8,
    service: 'Car Wash',
    price: 349,
    image: '/assets/users/ramesh.jpg',
  },
  {
    name: 'Divya Patil',
    experience: '3 yrs',
    rating: 4.7,
    service: 'Home Deep Cleaning',
    price: 599,
    image: '/assets/users/divya.jpg',
  },
];

export const testimonials = [
  {
    name: 'Amit',
    feedback: 'Fast service and very professional!',
  },
  {
    name: 'Priya',
    feedback: 'Loved the verified pros. Safe and on time!',
  },
  {
    name: 'Rohit',
    feedback: 'My AC was fixed in no time. Highly recommend!',
  },
  {
    name: 'Kavita',
    feedback: 'The cleaning staff was polite and did a great job.',
  },
  {
    name: 'Suresh',
    feedback: 'Easy to book and affordable prices.',
  },
  {
    name: 'Meena',
    feedback: 'Found a great salon expert through ServeSync!',
  },
];
